name: streama
services:
  streama-api:
    container_name: streama-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules # prevents host node_modules from overwriting container's
    environment:
      NODE_ENV: development
    networks:
      - db

  streama-app:
    container_name: streama-app
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # prevents host node_modules from overwriting container's
    environment:
      NODE_ENV: development
    networks:
      - db

networks:
  db:
    external: true
