FROM oven/bun:alpine AS base

WORKDIR /usr/src/api

# Install dependencies for development
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Copy source code
COPY . ./

# Expose port
EXPOSE ${PORT}

# Run in development mode with watch
CMD ["bun", "run", "start:dev"]
